/**
 * Appcelerator Titanium Mobile
 * Copyright (c) 2011-2012 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
#include <stdio.h>
#include <v8.h>
#include <string.h>

#include "V8Util.h"
#include "StringTable.h"

#define TAG "StringTable"

//Step one: Naive attempt
typedef struct StringTableEntry {
	const char *cString;
	void *jsString;
} StringTableEntry;

StringTableEntry InternalLookupTable[] = {
	{"", NULL },
	{"accessibilityHidden", NULL },
	{"accessibilityHint", NULL },
	{"accessibilityLabel", NULL },
	{"accessibilityValue", NULL },
	{"accuracy", NULL },
	{"action", NULL },
	{"actionView", NULL },
	{"activeTab", NULL },
	{"activeTabBackgroundColor", NULL },
	{"activity", NULL },
	{"activityEnterAnimation", NULL },
	{"activityExitAnimation", NULL },
	{"addedtotab", NULL },
	{"address", NULL },
	{"allowBackground", NULL },
	{"altitude", NULL },
	{"altitudeAccuracy", NULL },
	{"anchorPoint", NULL },
	{"androidback", NULL },
	{"androidcamera", NULL },
	{"androidfocus", NULL },
	{"androidsearch", NULL },
	{"androidView", NULL },
	{"androidvoldown", NULL },
	{"androidvolup", NULL },
	{"animate", NULL },
	{"animated", NULL },
	{"anniversary", NULL },
	{"annotation", NULL },
	{"annotations", NULL },
	{"assistant", NULL },
	{"audioStreamType", NULL },
	{"auto", NULL },
	{"autocapitalization", NULL },
	{"autocorrect", NULL },
	{"autoLink", NULL },
	{"autoplay", NULL },
	{"autoreverse", NULL },
	{"autorotate", NULL },
	{"background", NULL },
	{"backgroundColor", NULL },
	{"backgroundDisabledColor", NULL },
	{"backgroundDisabledImage", NULL },
	{"backgroundFocusedColor", NULL },
	{"backgroundFocusedImage", NULL },
	{"backgroundGradient", NULL },
	{"backgroundImage", NULL },
	{"backgroundPadding", NULL },
	{"backgroundRepeat", NULL },
	{"backgroundSelectedColor", NULL },
	{"backgroundSelectedImage", NULL },
	{"baseUrl", NULL },
	{"baseURL", NULL },
	{"battery", NULL },
	{"birthday", NULL },
	{"blur", NULL },
	{"border", NULL },
	{"borderColor", NULL },
	{"borderRadius", NULL },
	{"borderWidth", NULL },
	{"bottom", NULL },
	{"brother", NULL },
	{"bubbles", NULL },
	{"button", NULL },
	{"buttonNames", NULL },
	{"byteOrder", NULL },
	{"canCancelEvents", NULL },
	{"cancel", NULL },
	{"cancelable", NULL },
	{"canScale", NULL },
	{"center", NULL },
	{"change", NULL },
	{"charset", NULL },
	{"checkable", NULL },
	{"checked", NULL },
	{"child", NULL },
	{"city", NULL },
	{"className", NULL },
	{"classNames", NULL },
	{"clearOnEdit", NULL },
	{"click", NULL },
	{"clicksource", NULL },
	{"close", NULL },
	{"code", NULL },
	{"collapse", NULL },
	{"color", NULL },
	{"complete", NULL },
	{"contentHeight", NULL },
	{"contentIntent", NULL },
	{"contentOffset", NULL },
	{"contentText", NULL },
	{"contentTitle", NULL },
	{"contentURL", NULL },
	{"contentView", NULL },
	{"contentWidth", NULL },
	{"coords", NULL },
	{"count", NULL },
	{"country", NULL },
	{"country_code", NULL },
	{"create", NULL },
	{"currentPage", NULL },
	{"currentPlaybackTime", NULL },
	{"data", NULL },
	{"date", NULL },
	{"dblclick", NULL },
	{"defaultImage", NULL },
	{"defaults", NULL },
	{"delay", NULL },
	{"deleteIntent", NULL },
	{"dest", NULL },
	{"destPosition", NULL },
	{"destroy", NULL },
	{"detail", NULL },
	{"direction", NULL },
	{"displayAddress", NULL },
	{"domain", NULL },
	{"domesticPartner", NULL },
	{"doubletap", NULL },
	{"dragend", NULL },
	{"duration", NULL },
	{"durationavailable", NULL },
	{"editable", NULL },
	{"ellipsize", NULL },
	{"email", NULL },
	{"enabled", NULL },
	{"enableReturnKey", NULL },
	{"enableZoomControls", NULL },
	{"endPlaybackTime", NULL },
	{"enterAnimation", NULL },
	{"error", NULL },
	{"errorcode", NULL },
	{"event", NULL },
	{"eventName", NULL },
	{"exitAnimation", NULL },
	{"exitOnClose", NULL },
	{"expand", NULL },
	{"father", NULL },
	{"file", NULL },
	{"filename", NULL },
	{"fill", NULL },
	{"filterAttribute", NULL },
	{"filterCaseInsensitive", NULL },
	{"finishRoot", NULL },
	{"firstName", NULL },
	{"flags", NULL },
	{"focus", NULL },
	{"focusable", NULL },
	{"focused", NULL },
	{"font", NULL },
	{"font-family", NULL },
	{"font-size", NULL },
	{"font-weight", NULL },
	{"footer", NULL },
	{"footerTitle", NULL },
	{"footerView", NULL },
	{"forward", NULL },
	{"frequency", NULL },
	{"friend", NULL },
	{"from", NULL },
	{"fullname", NULL },
	{"fullscreen", NULL },
	{"groupId", NULL },
	{"hasCheck", NULL },
	{"hasChild", NULL },
	{"header", NULL },
	{"headerTitle", NULL },
	{"headerView", NULL },
	{"heading", NULL },
	{"headingFilter", NULL },
	{"height", NULL },
	{"hideAnnotationWhenTouchMap", NULL },
	{"highlightedColor", NULL },
	{"hintText", NULL },
	{"home", NULL },
	{"homepage", NULL },
	{"horizontal", NULL },
	{"horizontalWrap", NULL },
	{"html", NULL },
	{"icon", NULL },
	{"iconified", NULL },
	{"iconifiedByDefault", NULL },
	{"iconLevel", NULL },
	{"id", NULL },
	{"ignoreSslError", NULL },
	{"image", NULL },
	{"images", NULL },
	{"index", NULL },
	{"initialPlaybackTime", NULL },
	{"instantMessage", NULL },
	{"intent", NULL },
	{"isDialog", NULL },
	{"isTab", NULL },
	{"isUserGesture", NULL },
	{"itemId", NULL },
	{"keepScreenOn", NULL },
	{"keyboardType", NULL },
	{"keyCode", NULL },
	{"keypressed", NULL },
	{"lastName", NULL },
	{"latitude", NULL },
	{"latitudeDelta", NULL },
	{"layout", NULL },
	{"layoutId", NULL },
	{"layoutName", NULL },
	{"ledARGB", NULL },
	{"ledOffMS", NULL },
	{"ledOnMS", NULL },
	{"left", NULL },
	{"leftButton", NULL },
	{"leftImage", NULL },
	{"leftView", NULL },
	{"length", NULL },
	{"level", NULL },
	{"load", NULL },
	{"loadstate", NULL },
	{"loadState", NULL },
	{"location", NULL },
	{"longclick", NULL },
	{"longitude", NULL },
	{"longitudeDelta", NULL },
	{"longpress", NULL },
	{"magneticHeading", NULL },
	{"manager", NULL },
	{"mapType", NULL },
	{"max", NULL },
	{"maxAge", NULL },
	{"maxLength", NULL },
	{"mediaControlStyle", NULL },
	{"menu", NULL },
	{"message", NULL },
	{"messageId", NULL },
	{"messageid", NULL },
	{"messenger", NULL },
	{"messengerReceiver", NULL },
	{"middleName", NULL },
	{"mimeType", NULL },
	{"min", NULL },
	{"minAge", NULL },
	{"minRowHeight", NULL },
	{"minUpdateDistance", NULL },
	{"minUpdateTime", NULL },
	{"minuteInterval", NULL },
	{"mobile", NULL },
	{"modal", NULL },
	{"mother", NULL },
	{"msgActivityCreatedId", NULL },
	{"name", NULL },
	{"navBarHidden", NULL },
	{"newintent", NULL },
	{"nickname", NULL },
	{"note", NULL },
	{"number", NULL },
	{"ok", NULL },
	{"okid", NULL },
	{"onCreateOptionsMenu", NULL },
	{"onCreateWindow", NULL },
	{"onHomeIconItemSelected", NULL },
	{"onPrepareOptionsMenu", NULL },
	{"onReceived", NULL },
	{"opacity", NULL },
	{"open", NULL },
	{"options", NULL },
	{"order", NULL },
	{"organization", NULL },
	{"orientationModes", NULL },
	{"other", NULL },
	{"overScrollMode", NULL },
	{"packageName", NULL },
	{"pagingControlTimeout", NULL },
	{"parent", NULL },
	{"partner", NULL },
	{"password", NULL },
	{"passwordMask", NULL },
	{"pause", NULL },
	{"persistent", NULL },
	{"phone", NULL },
	{"pinch", NULL },
	{"pincolor", NULL },
	{"pinImage", NULL },
	{"places", NULL },
	{"play", NULL },
	{"playableDuration", NULL },
	{"playbackstate", NULL },
	{"pluginState", NULL },
	{"position", NULL },
	{"postalCode", NULL },
	{"postlayout", NULL },
	{"power", NULL },
	{"preferredProvider", NULL },
	{"preload", NULL },
	{"previousIndex", NULL },
	{"previousTab", NULL },
	{"provider", NULL },
	{"reason", NULL },
	{"referredBy", NULL },
	{"region", NULL },
	{"region1", NULL },
	{"region2", NULL },
	{"regionchanged", NULL },
	{"regionFit", NULL },
	{"relatedNames", NULL },
	{"repeat", NULL },
	{"repeatCount", NULL },
	{"requestCode", NULL },
	{"restart", NULL },
	{"resultCode", NULL },
	{"resume", NULL },
	{"returnKeyType", NULL },
	{"reverse", NULL },
	{"right", NULL },
	{"rightButton", NULL },
	{"rightImage", NULL },
	{"rightView", NULL },
	{"rotate", NULL },
	{"row", NULL },
	{"rowData", NULL },
	{"rowHeight", NULL },
	{"scale", NULL },
	{"scalesPageToFit", NULL },
	{"scalingMode", NULL },
	{"scroll", NULL },
	{"scrollEnabled", NULL },
	{"scrollend", NULL },
	{"scrollingEnabled", NULL },
	{"scrollType", NULL },
	{"search", NULL },
	{"searchAsChild", NULL },
	{"searchMode", NULL },
	{"section", NULL },
	{"selectedBackgroundColor", NULL },
	{"selectedBackgroundImage", NULL },
	{"selectedIndex", NULL },
	{"selectionIndicator", NULL },
	{"separatorColor", NULL },
	{"showAsAction", NULL },
	{"showHorizontalScrollIndicator", NULL },
	{"showPagingControl", NULL },
	{"showProgress", NULL },
	{"showVerticalScrollIndicator", NULL },
	{"singletap", NULL },
	{"sister", NULL },
	{"size", NULL },
	{"softKeyboardOnFocus", NULL },
	{"sound", NULL },
	{"source", NULL },
	{"sourceLength", NULL },
	{"sourcePosition", NULL },
	{"speed", NULL },
	{"spouse", NULL },
	{"src", NULL },
	{"start", NULL },
	{"startMode", NULL },
	{"state", NULL },
	{"status", NULL },
	{"stop", NULL },
	{"street", NULL },
	{"street1", NULL },
	{"style", NULL },
	{"submit", NULL },
	{"submitEnabled", NULL },
	{"subtitle", NULL },
	{"subtitleid", NULL },
	{"success", NULL },
	{"swipe", NULL },
	{"tab", NULL },
	{"tabOpen", NULL },
	{"tabs", NULL },
	{"tabsBackgroundColor", NULL },
	{"tabsBackgroundSelectedColor", NULL },
	{"tag", NULL },
	{"text", NULL },
	{"textAlign", NULL },
	{"textid", NULL },
	{"thumbOffset", NULL },
	{"thumbSize", NULL },
	{"tickerText", NULL },
	{"time", NULL },
	{"timeout", NULL },
	{"timestamp", NULL },
	{"title", NULL },
	{"titleCondensed", NULL },
	{"titleid", NULL },
	{"titleOff", NULL },
	{"titleOn", NULL },
	{"titlePrompt", NULL },
	{"titlepromptid", NULL },
	{"to", NULL },
	{"top", NULL },
	{"touchcancel", NULL },
	{"touchEnabled", NULL },
	{"touchend", NULL },
	{"touchmove", NULL },
	{"touchstart", NULL },
	{"transform", NULL },
	{"trueHeading", NULL },
	{"twofingertap", NULL },
	{"type", NULL },
	{"unfocused", NULL },
	{"updateCurrentIntent", NULL },
	{"uri", NULL },
	{"url", NULL },
	{"useActivityWindow", NULL },
	{"userLocation", NULL },
	{"username", NULL },
	{"value", NULL },
	{"velocity", NULL },
	{"vertical", NULL },
	{"verticalAlign", NULL },
	{"vibratePattern", NULL },
	{"view", NULL },
	{"views", NULL },
	{"visible", NULL },
	{"visibleItems", NULL },
	{"volume", NULL },
	{"when", NULL },
	{"width", NULL },
	{"window", NULL },
	{"windowId", NULL },
	{"windowPixelFormat", NULL },
	{"windowSoftInputMode", NULL },
	{"wordWrap", NULL },
	{"work", NULL },
	{"x", NULL },
	{"y", NULL },
	{"z", NULL },
	{"zIndex", NULL },
	{"zoomEnabled", NULL }
};

int InternalLookupTableCount = sizeof(InternalLookupTable) / sizeof(StringTableEntry);



using namespace titanium;

int StringTable::jsStringToStringTableIndex(v8::Handle<v8::String> jsString)
{
	int left = 1;
	int right = InternalLookupTableCount-1;
	v8::String::AsciiValue ascii(jsString);
	const char * value = *ascii;

	while (left <= right) {
		int middle = (left + right) / 2;
		int comparison = strcmp(value, InternalLookupTable[middle].cString);
		// Left    (-)     Middle(0)    (+)     Right

		if (comparison == 0) {
			return middle;
		}
		if (comparison > 0) {
			right = middle - 1;
		} else {
			left = middle + 1;
		}
	}
	return 0;
}

bool StringTable::stringTableIndexValid(int index)
{
	return (index > 0) && (index < InternalLookupTableCount);
}

v8::Handle<v8::Value> StringTable::stringTableIndexToJsString(int index)
{
	if (!StringTable::stringTableIndexValid(index)) {
		return v8::Null();
	}
	return StringTable::stringTableIndexToJsStringUnsafe(index);
}

v8::Handle<v8::String> StringTable::stringTableIndexToJsStringUnsafe(int index)
{
	const char * result = InternalLookupTable[index].cString;
	return IMMUTABLE_STRING_LITERAL_FROM_ARRAY(result, strlen(result));
}
